import {
  UserFormApp,
  SignupForm,
  // CounterApp,
  // Dropdown,
  // ColorPicker,
  // colorPickerOptions,
  // TodoComponent,
  // CafeFeedbackComponent,
  // PhonebookEditor,
  // LoginForm,
  // ProductReviewForm,
  // ModalApp,
  // Tabs,
  // initialTabs,
  // Example,
  // ReaderComponent,
  // publication,
  // Pokemon,
  // MaterialRenderComponent,
  // HooksSignupForm,
  // HooksColorPicker,
  // HooksCounter,
  // HooksClock,
  // AppBar,
  // SkipEffectOnFirstRender,
  // HooksPokemon,
  // HooksUseReduserCounter,
  // Friends,
  // NewsComponent,
  // LoadMoreComponent,
  // ContextApp,
} from '@/components';

export const supportConfig = [
  {
    path: 'UserFormApp',
    label: 'UserForm',
    description: 'Lorem lorem lorem',
    element: <UserFormApp />,
  },
  {
    path: 'SignupForm',
    label: 'UseLocalStorage',
    description: 'Lorem lorem lorem',
    element: <SignupForm />,
  },
  // {
  //   path: 'CounterApp',
  //   label: 'Counter',
  //   description: 'Lorem lorem lorem',
  //   element: <CounterApp />,
  // },
  // {
  //   path: 'Dropdown',
  //   label: 'Dropdown',
  //   description: 'Lorem lorem lorem',
  //   element: <Dropdown />,
  // },
  // {
  //   path: 'ColorPicker',
  //   label: 'ColorPicker',
  //   description: 'Lorem lorem lorem',
  //   element: <ColorPicker options={colorPickerOptions} />,
  // },
  // {
  //   path: 'TodoComponent',
  //   label: 'Todo',
  //   description: 'Lorem lorem lorem',
  //   element: <TodoComponent />,
  // },
  // {
  //   path: 'CafeFeedbackComponent',
  //   label: 'CafeFeedback',
  //   description: 'Lorem lorem lorem',
  //   element: <CafeFeedbackComponent />,
  // },
  // {
  //   path: 'PhonebookEditor',
  //   label: 'Phonebook',
  //   description: 'Lorem lorem lorem',
  //   element: <PhonebookEditor />,
  // },
  // {
  //   path: 'LoginForm',
  //   label: 'LoginForm',
  //   description: 'Lorem lorem lorem',
  //   element: <LoginForm />,
  // },
  // {
  //   path: 'ProductReviewForm',
  //   label: 'ProductReviewForm',
  //   description: 'Lorem lorem lorem',
  //   element: <ProductReviewForm />,
  // },
  // {
  //   path: 'ModalApp',
  //   label: 'Modal',
  //   description: 'Lorem lorem lorem',
  //   element: <ModalApp />,
  // },
  // {
  //   path: 'Tabs',
  //   label: 'Tabs',
  //   description: 'Lorem lorem lorem',
  //   element: <Tabs items={initialTabs} />,
  // },
  // {
  //   path: 'Example',
  //   label: 'Player',
  //   description: 'Lorem lorem lorem',
  //   element: <Example />,
  // },
  // {
  //   path: 'ReaderComponent',
  //   label: 'Reader',
  //   description: 'Lorem lorem lorem',
  //   element: <ReaderComponent items={publication} />,
  // },
  // {
  //   path: 'Pokemon',
  //   label: 'Pokemon',
  //   description: 'Lorem lorem lorem',
  //   element: <Pokemon />,
  // },
  // {
  //   path: 'MaterialRenderComponent',
  //   label: 'Materials',
  //   description: 'Lorem lorem lorem',
  //   element: <MaterialRenderComponent />,
  // },
  // {
  //   path: 'HooksSignupForm',
  //   label: 'HooksSignupForm',
  //   description: 'Lorem lorem lorem',
  //   element: <HooksSignupForm />,
  // },
  // {
  //   path: 'HooksColorPicker',
  //   label: 'HooksColorPicker',
  //   description: 'Lorem lorem lorem',
  //   element: <HooksColorPicker options={colorPickerOptions} />,
  // },
  // {
  //   path: 'HooksCounter',
  //   label: 'HooksCounter',
  //   description: 'Lorem lorem lorem',
  //   element: <HooksCounter />,
  // },
  // {
  //   path: 'HooksClock',
  //   label: 'HooksClock',
  //   description: 'Lorem lorem lorem',
  //   element: <HooksClock />,
  // },
  // {
  //   path: 'AppBar',
  //   label: 'AppBarComponent',
  //   description: 'Lorem lorem lorem',
  //   element: <AppBar />,
  // },
  // {
  //   path: 'SkipEffectOnFirstRender',
  //   label: 'SkipEffectOnFirstRender',
  //   description: 'Lorem lorem lorem',
  //   element: <SkipEffectOnFirstRender />,
  // },
  // {
  //   path: 'HooksPokemon',
  //   label: 'HooksPokemon',
  //   description: 'Lorem lorem lorem',
  //   element: <HooksPokemon />,
  // },
  // {
  //   path: 'HooksUseReduserCounter',
  //   label: 'HooksUseReduserCounter',
  //   description: 'Lorem lorem lorem',
  //   element: <HooksUseReduserCounter />,
  // },
  // {
  //   path: 'Friends',
  //   label: 'Friends',
  //   description: 'Lorem lorem lorem',
  //   element: <Friends />,
  // },
  // {
  //   path: 'NewsComponent',
  //   label: 'News',
  //   description: 'Lorem lorem lorem',
  //   element: <NewsComponent />,
  // },
  // {
  //   path: 'LoadMoreComponent',
  //   label: 'LoadMoreComponent',
  //   description: 'Lorem lorem lorem',
  //   element: <LoadMoreComponent />,
  // },
  // {
  //   path: 'ContextApp',
  //   label: 'ContextAlert',
  //   description: 'Lorem lorem lorem',
  //   element: <ContextApp />,
  // },
];
