import {
  UserFormApp,
  SignupForm,
  CounterApp,
  Dropdown,
  ColorPicker,
  colorPickerOptions,
  TodoComponent,
  CafeFeedbackComponent,
  PhonebookEditor,
  LoginForm,
  ProductReviewForm,
  ModalApp,
  Tabs,
  initialTabs,
  Example,
  ReaderComponent,
  publication,
  Pokemon,
  MaterialRenderComponent,
  HooksSignupForm,
  HooksColorPicker,
  HooksCounter,
  HooksClock,
  AppBar,
  SkipEffectOnFirstRender,
  HooksPokemon,
  HooksUseReduserCounter,
  Friends,
  NewsComponent,
  LoadMoreComponent,
  ContextApp,
} from '@/components';

export const supportConfig = [
  { path: 'UserForm', label: 'UserForm', element: <UserFormApp /> },
  { path: 'SignupForm', label: 'UseLocalStorage', element: <SignupForm /> },
  { path: 'Counter', label: 'Counter', element: <CounterApp /> },
  { path: 'Dropdown', label: 'Dropdown', element: <Dropdown /> },
  {
    path: 'ColorPicker',
    label: 'ColorPicker',
    element: <ColorPicker options={colorPickerOptions} />,
  },
  { path: 'TodoComponent', label: 'Todo', element: <TodoComponent /> },
  {
    path: 'CafeFeedbackComponent',
    label: 'CafeFeedback',
    element: <CafeFeedbackComponent />,
  },
  {
    path: 'PhonebookEditor',
    label: 'Phonebook',
    element: <PhonebookEditor />,
  },
  { path: 'LoginForm', label: 'LoginForm', element: <LoginForm /> },
  {
    path: 'ProductReviewForm',
    label: 'ProductReviewForm',
    element: <ProductReviewForm />,
  },
  { path: 'ModalApp', label: 'Modal', element: <ModalApp /> },
  { path: 'Tabs', label: 'Tabs', element: <Tabs items={initialTabs} /> },
  { path: 'Example', label: 'Player', element: <Example /> },
  {
    path: 'ReaderComponent',
    label: 'Reader',
    element: <ReaderComponent items={publication} />,
  },
  { path: 'Pokemon', label: 'Pokemon', element: <Pokemon /> },
  {
    path: 'MaterialRenderComponent',
    label: 'Materials',
    element: <MaterialRenderComponent />,
  },
  {
    path: 'HooksSignupForm',
    label: 'HooksSignupForm',
    element: <HooksSignupForm />,
  },
  {
    path: 'HooksColorPicker',
    label: 'HooksColorPicker',
    element: <HooksColorPicker options={colorPickerOptions} />,
  },
  { path: 'HooksCounter', label: 'HooksCounter', element: <HooksCounter /> },
  { path: 'HooksClock', label: 'HooksClock', element: <HooksClock /> },
  { path: 'AppBar', label: 'AppBarComponent', element: <AppBar /> },
  {
    path: 'SkipEffectOnFirstRender',
    label: 'SkipEffectOnFirstRender',
    element: <SkipEffectOnFirstRender />,
  },
  { path: 'HooksPokemon', label: 'HooksPokemon', element: <HooksPokemon /> },
  {
    path: 'HooksUseReduserCounter',
    label: 'HooksUseReduserCounter',
    element: <HooksUseReduserCounter />,
  },
  { path: 'Friends', label: 'Friends', element: <Friends /> },
  { path: 'NewsComponent', label: 'News', element: <NewsComponent /> },
  {
    path: 'LoadMoreComponent',
    label: 'LoadMoreComponent',
    element: <LoadMoreComponent />,
  },
  { path: 'ContextApp', label: 'ContextAlert', element: <ContextApp /> },
];
